backend:
  name: git-gateway
  branch: main

media_folder: "img/products"
public_folder: "/img/products"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} â€” ${{price}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Mercado Pago Link", name: "mp_link", widget: "string", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
